export const SUBMIT_QUESTION = 'submitquestion';
export const PREV_QUESTION = 'prevquestion';
export const NEXT_QUESTION = 'nextquestion';
export const PLAY_MODULE =  'playmodule';
export const RANDOM_PLAY = 'randomplay';
export const CHANGE_INDEX = 'changeindex';
export const CHANGE_INDEX_BYID = 'changeindexbyid';
export const SIDE_OPEN_CHANGE = 'sideopenchange';
export const SIDE_CLICK = 'sideclick';
export const PREV_EXAMPLE = 'prevexample';
export const NEXT_EXAMPLE = 'nextexample';
export const CHANGE_EXAMPLE = 'changeexmaple';
export const PREV_EXERCISE = 'prevexercise';
export const NEXT_EXERCISE = 'nextexercise';
export const CHANGE_EXERCISE = 'changeexercise';
export const PREV_PROBLEM = 'prevproblem';
export const NEXT_PROBLEM = 'nextproblem';
export const CHANGE_PROBLEM = 'changeproblem';
export const PREV_DIY = 'prevdiy'
export const NEXT_DIY = 'nextdiy';
export const CHANGE_DIY = 'changediy';
export const PREV_QUIZ = 'prevquiz';
export const NEXT_QUIZ = 'nextquiz';
export const CHANGE_QUIZ = 'changequiz';
export const CHANGE_EXAMPLE_INDEX = 'changeexampleindex'
export const CHANGE_EXERCISE_INDEX = 'changeexerciseindex'
export const CHANGE_PROBLEM_INDEX = 'changeproblemindex'
export const CHANGE_DIY_INDEX = 'changediyindex'
export const SEARCH = 'search'
export const CHANGE_QUIZ_DATA = 'changequizdata'
export const CHANGE_EXAMPLE_DATA = 'changeexampleindexdata'
export const CHANGE_EXERCISE_DATA = 'changeexerciseindexdata'
export const CHANGE_PROBLEM__DATA = 'changeproblemindexdata'
export const CHANGE_DIY_DATA = 'changediyindexdata'
export const LOAD_DATA = 'loaddata'

// export const changequizdata = createAction(CHANGE_QUIZ_DATA);
// export const changeexampleindexdata = createAction(CHANGE_EXAMPLE_INDEX_DATA);
// export const changeexerciseindexdata = createAction(CHANGE_EXERCISE_INDEX_DATA);
// export const changeproblemindexdata = createAction(CHANGE_PROBLEM_INDEX_DATA);
// export const changediyindexdata = createAction(CHANGE_DIY_INDEX_DATA);
