// reducers/index.js
import { combineReducers } from 'redux' // 利用combineReducers 合并reducers
import { routerReducer } from 'react-router-redux' // 将routerReducer一起合并管理
// import submit from './submit' // 引入update这个reducer

// export default combineReducers({
//     submit,
//     routing: routerReducer
// })

import {handleActions} from 'redux-actions';
import {SUBMIT_QUESTION, PREV_QUESTION, NEXT_QUESTION, CHANGE_INDEX, RANDOM_PLAY,CHANGE_INDEX_BYID,SIDE_OPEN_CHANGE,SIDE_CLICK,PREV_EXAMPLE,NEXT_EXAMPLE,CHANGE_EXAMPLE,NEXT_EXERCISE,PREV_EXERCISE,CHANGE_EXERCISE
,NEXT_PROBLEM,PREV_PROBLEM,CHANGE_PROBLEM
,NEXT_DIY,PREV_DIY,CHANGE_DIY,
PREV_QUIZ,NEXT_QUIZ,CHANGE_QUIZ,
CHANGE_EXAMPLE_INDEX,
CHANGE_EXERCISE_INDEX,
CHANGE_PROBLEM_INDEX,
CHANGE_DIY_INDEX,
CHANGE_QUIZ_DATA,
CHANGE_EXAMPLE_DATA,
CHANGE_EXERCISE_DATA,
CHANGE_PROBLEM_DATA,
CHANGE_DIY_DATA,
LOAD_DATA,
SEARCH,
LOAD_COMPLETE
} from '../actions/constants.js';

// import Data from '../data.js'


// export default handleActions({
let question =  handleActions({
	[SUBMIT_QUESTION]: (state,action) => {
		return {
			exerciseData:state.exerciseData,
			index: state.index,
			diyData:state.diyData,
			problemData:state.problemData,
			complete:state.complete,
			examplechapter:state.examplechapter,
			exercisechapter:state.exercisechapter,
			problemchapter:state.problemchapter,
			diychapter:state.diychapter,
			questionData: state.questionData,
			current:state.current,
			exampleIndex:state.exampleIndex,
			exerciseIndex:state.exerciseIndex,
			problemIndex: state.problemIndex,
			quizIndex:state.quizIndex,
			diyIndex:state.diyIndex,
			exampleData:state.exampleData,
			allData:state.allData,
			quizdata: state.quizdata,
		}
	},
	[PREV_QUESTION]: (state,action) => {
		return {
			exerciseData:state.exerciseData,
			index: state.index == 0 ? 0 : state.index-1,
			examplechapter:state.examplechapter,
			exercisechapter:state.exercisechapter,
			problemchapter:state.problemchapter,
			diychapter:state.diychapter,
			questionData: state.questionData,
			current:state.current,
			exampleIndex:state.exampleIndex,
			exerciseIndex:state.exerciseIndex,
			problemIndex: state.problemIndex,
			quizIndex:state.quizIndex,
			diyIndex:state.diyIndex,
			exampleData:state.exampleData,
			allData:state.allData,
			quizdata: state.quizdata,
		}
	},
	[NEXT_QUESTION]: (state,action) => {
		return {
			exerciseData:state.exerciseData,
			index: state.index+1,
			examplechapter:state.examplechapter,
			exercisechapter:state.exercisechapter,
			problemchapter:state.problemchapter,
			diychapter:state.diychapter,
			questionData: state.questionData,
			current:state.current,
			exampleIndex:state.exampleIndex,
			exerciseIndex:state.exerciseIndex,
			problemIndex: state.problemIndex,
			quizIndex:state.quizIndex,
			diyIndex:state.diyIndex,
			exampleData:state.exampleData,
			allData:state.allData,
			quizdata: state.quizdata,
		}
	},
	[CHANGE_INDEX]: (state,action) => {
		// console.log(action.payload);
		//console.log(Data);
		// console.log(Data[i].fields.code);
		for(var i=0;i<Data.length;i++){
			if(Data[i].fields.code==action.payload){
				state.index=i;
			}
		}
		return {
			exerciseData:state.exerciseData,
			index: state.index,
			diyData:state.diyData,
			problemData:state.problemData,
			complete:state.complete,
			examplechapter:state.examplechapter,
			exercisechapter:state.exercisechapter,
			problemchapter:state.problemchapter,
			diychapter:state.diychapter,
			questionData: state.questionData,
			current:state.current,
			exampleIndex:state.exampleIndex,
			exerciseIndex:state.exerciseIndex,
			diyIndex:state.diyIndex,
			quizIndex:state.quizIndex,
			problemIndex: state.problemIndex,
			exampleData:state.exampleData,
			allData:state.allData,
			quizdata: state.quizdata,
		}
	},
	[CHANGE_INDEX_BYID]: (state,action) => {
		state.index=action.payload;
		return {
			exerciseData:state.exerciseData,
			index: state.index,
			diyData:state.diyData,
			problemData:state.problemData,
			complete:state.complete,
			examplechapter:state.examplechapter,
			exercisechapter:state.exercisechapter,
			problemchapter:state.problemchapter,
			diychapter:state.diychapter,
			questionData: state.questionData,
			current:state.current,
			exampleIndex:state.exampleIndex,
			exerciseIndex:state.exerciseIndex,
			problemIndex: state.problemIndex,
			quizIndex:state.quizIndex,
			diyIndex:state.diyIndex,
			exampleData:state.exampleData,
			allData:state.allData,
			quizdata: state.quizdata,
		}
	},
	[CHANGE_EXAMPLE]: (state,action) => {
		return {
			exerciseData:state.exerciseData,
			index: state.index,
			diyData:state.diyData,
			problemData:state.problemData,
			complete:state.complete,
			examplechapter:action.payload,
			exercisechapter:state.exercisechapter,
			problemchapter:state.problemchapter,
			diychapter:state.diychapter,
			questionData: state.questionData,
			current:state.current,
			exampleIndex:state.exampleIndex,
			exerciseIndex:state.exerciseIndex,
			problemIndex: state.problemIndex,
			quizIndex:state.quizIndex,
			diyIndex:state.diyIndex,
			exampleData:state.exampleData,
			allData:state.allData,
			quizdata: state.quizdata,
		}
	},
	[CHANGE_EXERCISE]: (state,action) => {
		
		return {
			exerciseData:state.exerciseData,
			index: state.index,
			diyData:state.diyData,
			problemData:state.problemData,
			complete:state.complete,
			exercisechapter:action.payload,
			examplechapter:state.examplechapter,
			problemchapter:state.problemchapter,
			diychapter:state.diychapter,
			questionData: state.questionData,
			current:state.current,
			exampleIndex:state.exampleIndex,
			exerciseIndex:state.exerciseIndex,
			problemIndex: state.problemIndex,
			quizIndex:state.quizIndex,
			diyIndex:state.diyIndex,
			exampleData:state.exampleData,
			allData:state.allData,
			quizdata: state.quizdata,
		}
	},
	[CHANGE_PROBLEM]: (state,action) => {
		return {
			exerciseData:state.exerciseData,
			index: state.index,
			diyData:state.diyData,
			problemData:state.problemData,
			complete:state.complete,
			problemchapter:action.payload,
			examplechapter:state.examplechapter,
			exercisechapter:state.exercisechapter,
			diychapter:state.diychapter,
			questionData: state.questionData,
			current:state.current,
			exampleIndex:state.exampleIndex,
			exerciseIndex:state.exerciseIndex,
			problemIndex: state.problemIndex,
			quizIndex:state.quizIndex,
			diyIndex:state.diyIndex,
			exampleData:state.exampleData,
			allData:state.allData,
			quizdata: state.quizdata,
		}
	},
	[CHANGE_DIY]: (state,action) => {
		return {
			exerciseData:state.exerciseData,
			index: state.index,
			diyData:state.diyData,
			problemData:state.problemData,
			complete:state.complete,
			diychapter:action.payload,
			examplechapter:state.examplechapter,
			exercisechapter:state.exercisechapter,
			problemchapter:state.problemchapter,
			questionData: state.questionData,
			current:state.current,
			exampleIndex:state.exampleIndex,
			exerciseIndex:state.exerciseIndex,
			problemIndex: state.problemIndex,
			quizIndex:state.quizIndex,
			diyIndex:state.diyIndex,
			exampleData:state.exampleData,
			allData:state.allData,
			quizdata: state.quizdata,
		}
	},
	['FETCH_THING']:(state,action) => {
		// console.log("fetc");
		// console.log(action.payload);
		return {
			questionData:action.payload,
			exerciseData:state.exerciseData,
			index: state.index,
			diyData:state.diyData,
			problemData:state.problemData,
			complete:state.complete,
			examplechapter:state.examplechapter,
			exercisechapter:state.exercisechapter,
			problemchapter:state.problemchapter,
			diychapter:state.diychapter,
			current:state.current,
			exampleIndex:state.exampleIndex,
			exerciseIndex:state.exerciseIndex,
			problemIndex: state.problemIndex,
			quizIndex:state.quizIndex,
			diyIndex:state.diyIndex,
			exampleData:state.exampleData,
			allData:state.allData,
			quizdata: state.quizdata,
		}
	},
	[SIDE_OPEN_CHANGE]: (state,action) => {
		return {
			exerciseData:state.exerciseData,
			index: state.index,
			diyData:state.diyData,
			problemData:state.problemData,
			complete:state.complete,
			examplechapter:state.examplechapter,
			exercisechapter:state.exercisechapter,
			problemchapter:state.problemchapter,
			diychapter:state.diychapter,
			questionData: state.questionData,
			current:state.current,
			exampleIndex:state.exampleIndex,
			exerciseIndex:state.exerciseIndex,
			problemIndex: state.problemIndex,
			quizIndex:state.quizIndex,
			diyIndex:state.diyIndex,
			exampleData:state.exampleData,
			allData:state.allData,
			quizdata: state.quizdata,
		}
	},
	[SIDE_CLICK]: (state,action) => {
		return {
			current:action.payload,
			exerciseData:state.exerciseData,
			index: state.index,
			diyData:state.diyData,
			problemData:state.problemData,
			complete:state.complete,
			examplechapter:state.examplechapter,
			exercisechapter:state.exercisechapter,
			problemchapter:state.problemchapter,
			diychapter:state.diychapter,
			questionData: state.questionData,
			exampleIndex:state.exampleIndex,
			exerciseIndex:state.exerciseIndex,
			problemIndex: state.problemIndex,
			quizIndex:state.quizIndex,
			diyIndex:state.diyIndex,
			exampleData:state.exampleData,
			allData:state.allData,
			quizdata: state.quizdata,
		}
	},
	[PREV_EXAMPLE]: (state,action) => {
		return {
			exampleIndex: state.exampleIndex == 0 ? 0 : state.exampleIndex-1,
			questionData: state.questionData,
			current:state.current,
			exerciseData:state.exerciseData,
			index: state.index,
			diyData:state.diyData,
			problemData:state.problemData,
			complete:state.complete,
			examplechapter:state.examplechapter,
			exercisechapter:state.exercisechapter,
			problemchapter:state.problemchapter,
			diychapter:state.diychapter,
			exerciseIndex:state.exerciseIndex,
			problemIndex: state.problemIndex,
			quizIndex:state.quizIndex,
			diyIndex:state.diyIndex,
			exampleData:state.exampleData,
			allData:state.allData,
			quizdata: state.quizdata,
		}
	},
	[NEXT_EXAMPLE]: (state,action) => {
		// console.log(state.exampleData.length);
		return {
			exampleIndex: state.exampleIndex == state.exampleData.length-1 ? state.exampleData.length-1:state.exampleIndex+1,
			questionData: state.questionData,
			current:state.current,
			exerciseData:state.exerciseData,
			index: state.index,
			diyData:state.diyData,
			problemData:state.problemData,
			complete:state.complete,
			examplechapter:state.examplechapter,
			exercisechapter:state.exercisechapter,
			problemchapter:state.problemchapter,
			diychapter:state.diychapter,
			exerciseIndex:state.exerciseIndex,
			problemIndex: state.problemIndex,
			quizIndex:state.quizIndex,
			diyIndex:state.diyIndex,
			exampleData:state.exampleData,
			allData:state.allData,
			quizdata: state.quizdata,
		}
	},
	[PREV_EXERCISE]: (state,action) => {
		return {
			exampleIndex: state.exampleIndex,
			questionData: state.questionData,
			current:state.current,
			exerciseData:state.exerciseData,
			index: state.index,
			diyData:state.diyData,
			problemData:state.problemData,
			complete:state.complete,
			examplechapter:state.examplechapter,
			exercisechapter:state.exercisechapter,
			problemchapter:state.problemchapter,
			diychapter:state.diychapter,
			problemIndex: state.problemIndex,
			exerciseIndex:state.exerciseIndex == 0 ? 0 : state.exerciseIndex-1,
			quizIndex:state.quizIndex,
			diyIndex:state.diyIndex,
			exampleData:state.exampleData,
			allData:state.allData,
			quizdata: state.quizdata,
		}
	},
	[NEXT_EXERCISE]: (state,action) => {
		return {
			exampleIndex: state.exampleIndex,
			questionData: state.questionData,
			current:state.current,
			exerciseData:state.exerciseData,
			index: state.index,
			diyData:state.diyData,
			problemData:state.problemData,
			complete:state.complete,
			examplechapter:state.examplechapter,
			exercisechapter:state.exercisechapter,
			problemchapter:state.problemchapter,
			diychapter:state.diychapter,
			problemIndex: state.problemIndex,
			exerciseIndex:state.exerciseIndex == state.exerciseData.length-1 ? state.exerciseData.length-1:state.exerciseIndex+1,
			quizIndex:state.quizIndex,
			diyIndex:state.diyIndex,
			exampleData:state.exampleData,
			allData:state.allData,
			quizdata: state.quizdata,
		}
	},
	[PREV_PROBLEM]: (state,action) => {
		return {
			exampleIndex: state.exampleIndex,
			questionData: state.questionData,
			current:state.current,
			exerciseData:state.exerciseData,
			index: state.index,
			diyData:state.diyData,
			problemData:state.problemData,
			complete:state.complete,
			examplechapter:state.examplechapter,
			exercisechapter:state.exercisechapter,
			problemchapter:state.problemchapter,
			diychapter:state.diychapter,
			exerciseIndex:state.exerciseIndex,
			problemIndex:state.problemIndex == 0 ? 0:state.problemIndex-1,
			quizIndex:state.quizIndex,
			diyIndex:state.diyIndex,
			exampleData:state.exampleData,
			allData:state.allData,
			quizdata: state.quizdata,
		}
	},
	[NEXT_PROBLEM]: (state,action) => {
		// console.log("next");
		return {
			exampleIndex: state.exampleIndex,
			questionData: state.questionData,
			current:state.current,
			exerciseData:state.exerciseData,
			index: state.index,
			diyData:state.diyData,
			problemData:state.problemData,
			complete:state.complete,
			examplechapter:state.examplechapter,
			exercisechapter:state.exercisechapter,
			problemchapter:state.problemchapter,
			diychapter:state.diychapter,
			exerciseIndex:state.exerciseIndex,
			problemIndex:state.problemIndex == state.problemData.length-1 ? state.problemData.length-1:state.problemIndex+1,
			quizIndex:state.quizIndex,
			diyIndex:state.diyIndex,
			exampleData:state.exampleData,
			allData:state.allData,
			quizdata: state.quizdata,
		}
	},
	[PREV_DIY]: (state,action) => {
		return {
			exampleIndex: state.exampleIndex,
			questionData: state.questionData,
			current:state.current,
			exerciseData:state.exerciseData,
			index: state.index,
			diyData:state.diyData,
			problemData:state.problemData,
			complete:state.complete,
			examplechapter:state.examplechapter,
			exercisechapter:state.exercisechapter,
			problemchapter:state.problemchapter,
			diychapter:state.diychapter,
			exerciseIndex:state.exerciseIndex,
			problemIndex:state.problemIndex,
			quizIndex:state.quizIndex,
			diyIndex:state.diyIndex == 0 ? 0:state.diyIndex-1,
			exampleData:state.exampleData,
			allData:state.allData,
			quizdata: state.quizdata,
		}
	},
	[NEXT_DIY]: (state,action) => {
		return {
			exampleIndex: state.exampleIndex,
			questionData: state.questionData,
			current:state.current,
			exerciseData:state.exerciseData,
			index: state.index,
			diyData:state.diyData,
			problemData:state.problemData,
			complete:state.complete,
			examplechapter:state.examplechapter,
			exercisechapter:state.exercisechapter,
			problemchapter:state.problemchapter,
			diychapter:state.diychapter,
			exerciseIndex:state.exerciseIndex,
			problemIndex:state.problemIndex,
			quizIndex:state.quizIndex,
			diyIndex:state.diyIndex == 52 ? 52:state.diyIndex+1,
			exampleData:state.exampleData,
			allData:state.allData,
			quizdata: state.quizdata,
		}
	},
	[PREV_QUIZ]: (state,action) => {
		return {
			exampleIndex: state.exampleIndex,
			questionData: state.questionData,
			current:state.current,
			exerciseData:state.exerciseData,
			index: state.index,
			diyData:state.diyData,
			problemData:state.problemData,
			complete:state.complete,
			examplechapter:state.examplechapter,
			exercisechapter:state.exercisechapter,
			problemchapter:state.problemchapter,
			diychapter:state.diychapter,
			exerciseIndex:state.exerciseIndex,
			problemIndex:state.problemIndex,
			quizIndex:state.quizIndex == 0 ? 0:state.quizIndex-1,
			diyIndex:state.diyIndex,
			exampleData:state.exampleData,
			allData:state.allData,
			quizdata: state.quizdata,
		}
	},
	[NEXT_QUIZ]: (state,action) => {
		return {
			exampleIndex: state.exampleIndex,
			questionData: state.questionData,
			current:state.current,
			exerciseData:state.exerciseData,
			index: state.index,
			diyData:state.diyData,
			problemData:state.problemData,
			complete:state.complete,
			examplechapter:state.examplechapter,
			exercisechapter:state.exercisechapter,
			problemchapter:state.problemchapter,
			diychapter:state.diychapter,
			exerciseIndex:state.exerciseIndex,
			problemIndex:state.problemIndex,
			quizIndex:state.quizIndex == state.quizdata.length-1 ? state.quizdata.length-1:state.quizIndex+1,
			diyIndex:state.diyIndex,
			exampleData:state.exampleData,
			allData:state.allData,
			quizdata: state.quizdata,
		}
	},
	[CHANGE_EXAMPLE_INDEX]:(state,action) => ({
		// return {
			exampleIndex: action.payload,
			questionData: state.questionData,
			current:state.current,
			exerciseData:state.exerciseData,
			index: state.index,
			diyData:state.diyData,
			problemData:state.problemData,
			complete:state.complete,
			examplechapter:state.examplechapter,
			exercisechapter:state.exercisechapter,
			problemchapter:state.problemchapter,
			diychapter:state.diychapter,
			exerciseIndex:state.exerciseIndex,
			problemIndex:state.problemIndex,
			quizIndex:state.quizIndex,
			diyIndex:state.diyIndex ,
			exampleData:state.exampleData,
			allData:state.allData,
			quizdata: state.quizdata,
		// }
	}),
	[CHANGE_EXERCISE_INDEX]:(state,action) => {
		// console.log(action.payload);
		return {
			problemIndex: state.problemIndex,
			exampleIndex: state.exampleIndex,
			questionData: state.questionData,
			current:state.current,
			exerciseData:state.exerciseData,
			index: state.index,
			diyData:state.diyData,
			problemData:state.problemData,
			complete:state.complete,
			examplechapter:state.examplechapter,
			exercisechapter:state.exercisechapter,
			problemchapter:state.problemchapter,
			diychapter:state.diychapter,
			exerciseIndex:action.payload,
			quizIndex:state.quizIndex,
			diyIndex:state.diyIndex ,
			exampleData:state.exampleData,
			allData:state.allData,
			quizdata: state.quizdata,
		}
	},
	[CHANGE_PROBLEM_INDEX]:(state,action) => {
		return {
			problemIndex:action.payload,
			exampleIndex: state.exampleIndex,
			questionData: state.questionData,
			current:state.current,
			exerciseData:state.exerciseData,
			index: state.index,
			diyData:state.diyData,
			problemData:state.problemData,
			complete:state.complete,
			examplechapter:state.examplechapter,
			exercisechapter:state.exercisechapter,
			problemchapter:state.problemchapter,
			diychapter:state.diychapter,
			exerciseIndex:state.exerciseIndex,
			quizIndex:state.quizIndex,
			diyIndex:state.diyIndex,
			exampleData:state.exampleData,
			allData:state.allData,
			quizdata: state.quizdata,
		}
	},
	[CHANGE_DIY_INDEX]:(state,action) => {
		return {
			diyIndex:action.payload,
			exampleIndex: state.exampleIndex,
			questionData: state.questionData,
			current:state.current,
			exerciseData:state.exerciseData,
			index: state.index,
			diyData:state.diyData,
			problemData:state.problemData,
			complete:state.complete,
			examplechapter:state.examplechapter,
			exercisechapter:state.exercisechapter,
			problemchapter:state.problemchapter,
			diychapter:state.diychapter,
			problemIndex:state.problemIndex,
			quizIndex:state.quizIndex,
			exerciseIndex:state.exerciseIndex,
			exampleData:state.exampleData,
			allData:state.allData,
			quizdata: state.quizdata,
		}
	},
	[LOAD_DATA]:(state,action) => {
		return {
			exampleData:state.exampleData,
			allData:action.payload,
			diyIndex:state.diyIndex,
			exampleIndex: state.exampleIndex,
			questionData: state.questionData,
			current:state.current,
			exerciseData:state.exerciseData,
			index: state.index,
			diyData:state.diyData,
			problemData:state.problemData,
			complete:state.complete,
			examplechapter:state.examplechapter,
			exercisechapter:state.exercisechapter,
			problemchapter:state.problemchapter,
			diychapter:state.diychapter,
			problemIndex:state.problemIndex,
			quizIndex:state.quizIndex,
			exerciseIndex:state.exerciseIndex,
			quizdata: state.quizdata,
		}
	},
	[CHANGE_EXAMPLE_DATA]:(state,action) => {
		return {
			allData:state.allData,
			quizdata: state.quizdata,
			exampleData:action.payload,
			diyIndex:state.diyIndex,
			exampleIndex: state.exampleIndex,
			questionData: state.questionData,
			current:state.current,
			exerciseData:state.exerciseData,
			index: state.index,
			diyData:state.diyData,
			problemData:state.problemData,
			complete:state.complete,
			examplechapter:state.examplechapter,
			exercisechapter:state.exercisechapter,
			problemchapter:state.problemchapter,
			diychapter:state.diychapter,
			problemIndex:state.problemIndex,
			quizIndex:state.quizIndex,
			exerciseIndex:state.exerciseIndex 
		}
	},
	[CHANGE_EXERCISE_DATA]:(state,action) => {
		return {
			exerciseData:action.payload,
			allData:state.allData,
			quizdata: state.quizdata,
			exampleData:state.exampleData,
			diyIndex:state.diyIndex,
			exampleIndex: state.exampleIndex,
			questionData: state.questionData,
			current:state.current,
			index: state.index,
			diyData:state.diyData,
			problemData:state.problemData,
			complete:state.complete,
			examplechapter:state.examplechapter,
			exercisechapter:state.exercisechapter,
			problemchapter:state.problemchapter,
			diychapter:state.diychapter,
			problemIndex:state.problemIndex,
			quizIndex:state.quizIndex,
			exerciseIndex:state.exerciseIndex 
		}
	},
	[LOAD_COMPLETE]:(state,action) => {
			// console.log(action.payload);
		return {
			complete:action.payload,
			exerciseData:state.exerciseData,
			allData:state.allData,
			quizdata: state.quizdata,
			exampleData:state.exampleData,
			diyIndex:state.diyIndex,
			exampleIndex: state.exampleIndex,
			questionData: state.questionData,
			current:state.current,
			index: state.index,
			diyData:state.diyData,
			problemData:state.problemData,
			examplechapter:state.examplechapter,
			exercisechapter:state.exercisechapter,
			problemchapter:state.problemchapter,
			diychapter:state.diychapter,
			problemIndex:state.problemIndex,
			quizIndex:state.quizIndex,
			exerciseIndex:state.exerciseIndex 
		}
	},
	[CHANGE_PROBLEM_DATA]:(state,action) => {
		// console.log(action.payload);
		return {
			complete:state.complete,
			exerciseData:state.exerciseData,
			allData:state.allData,
			quizdata: state.quizdata,
			exampleData:state.exampleData,
			diyIndex:state.diyIndex,
			exampleIndex: state.exampleIndex,
			questionData: state.questionData,
			current:state.current,
			index: state.index,
			diyData:state.diyData,
			problemData:action.payload,
			examplechapter:state.examplechapter,
			exercisechapter:state.exercisechapter,
			problemchapter:state.problemchapter,
			diychapter:state.diychapter,
			problemIndex:state.problemIndex,
			quizIndex:state.quizIndex,
			exerciseIndex:state.exerciseIndex 
		}
	},
	[CHANGE_DIY_DATA]:(state,action) => {
		return {
			complete:state.complete,
			exerciseData:state.exerciseData,
			allData:state.allData,
			quizdata: state.quizdata,
			exampleData:state.exampleData,
			diyIndex:state.diyIndex,
			exampleIndex: state.exampleIndex,
			questionData: state.questionData,
			current:state.current,
			index: state.index,
			diyData:action.payload,
			problemData:state.problemData,
			examplechapter:state.examplechapter,
			exercisechapter:state.exercisechapter,
			problemchapter:state.problemchapter,
			diychapter:state.diychapter,
			problemIndex:state.problemIndex,
			quizIndex:state.quizIndex,
			exerciseIndex:state.exerciseIndex,
		}
	},
	[CHANGE_QUIZ_DATA]:(state,action) =>{
		return {
			complete:state.complete,
			exerciseData:state.exerciseData,
			allData:state.allData,
			quizdata: state.quizdata,
			exampleData:state.exampleData,
			diyIndex:state.diyIndex,
			exampleIndex: state.exampleIndex,
			questionData: state.questionData,
			current:state.current,
			index: state.index,
			diyData: state.diyData,
			quizdata:action.payload,
			problemData:state.problemData,
			examplechapter:state.examplechapter,
			exercisechapter:state.exercisechapter,
			problemchapter:state.problemchapter,
			diychapter:state.diychapter,
			problemIndex:state.problemIndex,
			quizIndex:state.quizIndex,
			exerciseIndex:state.exerciseIndex 
		}
	}
},{
	index:1,
	exampleIndex:0,
	exerciseIndex:0,
	problemIndex:0,
	diyIndex:0,
	quizIndex:0,
	allData:[],
	complete:[],
	exampleData:[],
	exerciseData:[],
	problemData: [],
	quizdata: [],
	diyData:[],
	current:'0',
	examplechapter:1,
	exercisechapter:3,
	problemchapter:1,
	diychapter:1,
})

let searchstate =  handleActions({

	[SEARCH]: (state,action) => {
		//console.log("payload",action.payload);
		return{
			searchType:action.payload.type,
			searchResult:action.payload.result,
		}
	}
},
	{
		searchValue:'',
		searchResult:[],
	}
)

let graph =  handleActions({

	['setchapter']: (state,action) => {
		// console.log("payload",action.payload);
		return{
			chapter:action.payload,
		}
	}
},
	{
		chapter:4,
	}
)
export default combineReducers({
    question,
    graph,
    searchstate,
    routing: routerReducer
})